Settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
        description="My API description",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="Awesome License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('front.urls')),
    path('api/', include('api.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quiz/',views.QuizApiView.as_view()),
    path('questions/',views.QuestionApiView.as_view()),
    path('quiz/<str:code>/', views.get_quiz),
    path('question/<str:code>/', views.get_question),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index,name='index'),
    path('quizzes/',views.quiz_list,name='quiz_list'),
    path('excel/<str:code>/',views.generate_excel,name='excel'),
    path('add-quiz/',views.quiz_create,name='quiz_create'),
    path('quiz-detail/<str:code>/',views.quiz_detail,name='quiz_detail'),
    path('question-create/<str:code>/',views.question_create,name='question_create'),
    path('question-detail/<str:code>/',views.question_detail,name='question_detail'),
    path('question-delete/<str:code>/',views.question_delete,name='question_delete'),
    path('question-update/<str:code>/',views.question_update,name='question_update'),
    path('answer-list/<str:code>/', views.answer_list, name='answer_list'),
    path('answer-detail/<str:code>/', views.answer_detail, name='answer_detail'),
    path('register/',views.register,name='register'),
    path('login/',views.log_in,name='login'),
    path('logout/',views.log_out,name='logout'),
]

templates/answer/detail.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<!-- Content Wrapper START -->
         <div class="main-content">
            <div class="page-header no-gutters">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between m-b-15">
                            <h4 class="m-b-0">Javoblar ro`yhati</h4>
                        </div>
                        <div class="d-flex align-items-center justify-content-between m-b-15">
                            <h4 class="m-b-0">Umumiy savollar: {{total}}</h4>
                            <h4 class="m-b-0">To`g`ri javoblar soni: {{correct}}</h4>
                            <h4 class="m-b-0">Noto`g`ri javoblar soni: {{in_correct}}</h4>
                        </div>
                        <div class="d-flex align-items-center justify-content-between m-b-15">
                            <h4 class="m-b-0">100 %</h4>
                            <h4 class="m-b-0">{{correct_percentage}} %</h4>
                            <h4 class="m-b-0">{{in_correct_percentage}} %</h4>
                        </div>
                        <div class="m-t-25">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Savol</th>
                                            <th scope="col">To`g`ri javob</th>
                                            <th scope="col">Kiritlgan javob</th>
                                            <th scope="col">Holat</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for d in details %}
                                        <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <td>{{d.question}}</td>
                                            <td>{{d.question.correct_answer.name}}</td>
                                            <td>{{d.user_answer.name}}</td>
                                            {% if d.is_correct %}
                                            <td><button class="btn btn-success btn-tone m-r-5">To`g`ri</button></td>
                                            {% else %}
                                            <td><button class="btn btn-danger btn-tone m-r-5">Noto`g`ri</button></td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" value="{{request.build_absolute_uri}}" aria-label="Recipient's username" aria-describedby="basic-addon2" id="path">
                    <div class="input-group-append">
                        <button class="btn btn-primary btn-tone m-r-5" onclick="CopyText()">
                            Nusxa olish
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Wrapper END -->
        <script>
            function CopyText() {
            var text = document.getElementById('path')
            text.select();
            document.execCommand('copy')
          }
          </script>
{% endblock %}

templates/answer/list.html
{% extends 'base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Quiz</h2>
    </div>
    <div class="card">
        <div class="card-body">
            <h4 style="display: inline;">Javoblar ro`yxat</h4>
            <a class="text-gray" href="{% url 'dashboard:excel' quiz.code %}">
                <button class="btn btn-primary btn-tone m-r-5">Natijalarni yuklash</button>
            </a>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Ism</th>
                                <th scope="col">Telefon raqam</th>
                                <th scope="col">Email</th>
                                <th scope="col">Natijalar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for a in answers %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{a.user_name}}</td>
                                <td>{{a.phone}}</td>
                                <td>{{a.email}}</td>
                                <td><a href="{% url 'dashboard:answer_detail' a.code %}">Natija</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}