Settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
        description="My API description",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="Awesome License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('front.urls')),
    path('api/', include('api.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quiz/',views.QuizApiView.as_view()),
    path('questions/',views.QuestionApiView.as_view()),
    path('quiz/<str:code>/', views.get_quiz),
    path('question/<str:code>/', views.get_question),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index,name='index'),
    path('quizzes/',views.quiz_list,name='quiz_list'),
    path('excel/<str:code>/',views.generate_excel,name='excel'),
    path('add-quiz/',views.quiz_create,name='quiz_create'),
    path('quiz-detail/<str:code>/',views.quiz_detail,name='quiz_detail'),
    path('question-create/<str:code>/',views.question_create,name='question_create'),
    path('question-detail/<str:code>/',views.question_detail,name='question_detail'),
    path('question-delete/<str:code>/',views.question_delete,name='question_delete'),
    path('question-update/<str:code>/',views.question_update,name='question_update'),
    path('answer-list/<str:code>/', views.answer_list, name='answer_list'),
    path('answer-detail/<str:code>/', views.answer_detail, name='answer_detail'),
    path('register/',views.register,name='register'),
    path('login/',views.log_in,name='login'),
    path('logout/',views.log_out,name='logout'),
]

templates/quiz/create.html
{% extends 'base.html' %}

{% block content %}

                
    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">Quiz</h2>
        </div>
        <div class="card">
            <div class="card-body">
                <h4>Quiz yaratish</h4>
                <div class="m-t-25" style="max-width: 700px">
                    <form method="post">{% csrf_token %}
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Nom</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPassword3" placeholder="..." name="name">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Saqlash</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->
  
{% endblock %}

templates/quiz/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Quiz</h2>
    </div>
    <div class="card">
        <div class="card-body">
            <a class="text-gray" href="{% url 'dashboard:answer_list' quiz.code %}">
                <button class="btn btn-primary btn-tone m-r-5">Natijalar</button>
            </a>
            <a class="text-gray" href="{% url 'dashboard:excel' quiz.code %}">
                <button class="btn btn-primary btn-tone m-r-5">Natijalarni yuklash</button>
            </a>
            <div class="d-flex justify-content-end">
                <a href="{% url 'dashboard:question_create' quiz.code %}"><button class="btn btn-primary btn-tone m-r-5">Savol qo`shish</button></a>
            </div>
            {% for question in questions %}
            <div class="container">
                <div class="d-flex justify-content-between" >
                    <h2 class="font-weight-normal m-b-10">{{forloop.counter}}. {{question.name}}</h2>
                    <a href="{% url 'dashboard:question_detail' question.code %}"><button class="btn btn-primary btn-tone m-r-5">Batafsil</button></a>
                    <button class="btn btn-primary btn-tone m-r-5" data-toggle="modal" data-target="#exampleModal{{forloop.counter}}">O`zgartirish</button>
                    <a href="{% url 'dashboard:question_delete' question.code %}"><button class="btn btn-danger btn-tone m-r-5">O`chirish</button></a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal{{forloop.counter}}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">{{question.name}}</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <i class="anticon anticon-close"></i>
                                </button>
                            </div>
                            <form method="post" action="{% url 'dashboard:question_update' question.code %}">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <div class="form-group row">
                                        <label for="inputPassword3" class="col-sm-2 col-form-label">Nom</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="inputPassword3" value="{{question.name}}" name="name">
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Yopish</button>
                                    <button type="submit" class="btn btn-primary">Saqlash</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                {% for option in question.options %}
                <div class="alert alert-{% if option.is_correct %}success{% else %}danger{% endif %}">
                    <p>{{option.name}}</p>
                </div>                  
                {% endfor %}
            </div>              
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/quiz/list.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<!-- Content Wrapper START -->
         <div class="main-content">
            <div class="page-header no-gutters">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between m-b-15">
                            <h4 class="m-b-0">Quizlar ro`yhati</h4>
                            <div class="card-toolbar">
                                <ul>
                                    <li>
                                        <a class="text-gray" href="{% url 'dashboard:quiz_create' %}">
                                            <button class="btn btn-primary btn-tone m-r-5">Quiz qo`shish</button>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="m-t-25">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Nom</th>
                                            <th scope="col">Harakatlar</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for q in quizzes %}
                                        <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <td><a href="{% url 'dashboard:quiz_detail' q.code %}">{{q.name}}</a></td>
                                            <td>{{q.all}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Wrapper END -->
        
{% endblock %}