Settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
        description="My API description",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="Awesome License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('front.urls')),
    path('api/', include('api.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quiz/',views.QuizApiView.as_view()),
    path('questions/',views.QuestionApiView.as_view()),
    path('quiz/<str:code>/', views.get_quiz),
    path('question/<str:code>/', views.get_question),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index,name='index'),
    path('quizzes/',views.quiz_list,name='quiz_list'),
    path('excel/<str:code>/',views.generate_excel,name='excel'),
    path('add-quiz/',views.quiz_create,name='quiz_create'),
    path('quiz-detail/<str:code>/',views.quiz_detail,name='quiz_detail'),
    path('question-create/<str:code>/',views.question_create,name='question_create'),
    path('question-detail/<str:code>/',views.question_detail,name='question_detail'),
    path('question-delete/<str:code>/',views.question_delete,name='question_delete'),
    path('question-update/<str:code>/',views.question_update,name='question_update'),
    path('answer-list/<str:code>/', views.answer_list, name='answer_list'),
    path('answer-detail/<str:code>/', views.answer_detail, name='answer_detail'),
    path('register/',views.register,name='register'),
    path('login/',views.log_in,name='login'),
    path('logout/',views.log_out,name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin Dashboard Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/logo/favicon.png' %}">

    <!-- page css -->
    <link href="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">

    <!-- Core css -->
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            {% if user.is_authenticated %}
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="{% url 'dashboard:index' %}">
                        <img src="{% static 'images/logo/logo.png' %}" alt="Logo" width="200px">
                        <img class="logo-fold" src="{% static 'images/logo/logo-fold.png' %}" alt="Logo" style="width: 200px;">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="{% url 'dashboard:index' %}">
                        <img src="{% static 'images/logo/logo-white.png' %}" alt="Logo" width="200px">
                        <img class="logo-fold" src="{% static 'images/logo/logo-fold-white.png' %}" alt="Logo" style="width: 200px;">
                    </a>
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                    <ul class="nav-right">
                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">
                                <div class="avatar avatar-image  m-h-10 m-r-15">
                                    <img src="{% static 'images/avatars/thumb-3.jpg' %}"  alt="">
                                </div>
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img src="{% static 'images/avatars/thumb-3.jpg' %}" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <p class="m-b-0 text-dark font-weight-semibold">{{user.username}}</p>
                                            <p class="m-b-0 opacity-07">{% if user.is_staff %}Admin {% else %}Foydalanuvchi{% endif %}</p>
                                        </div>
                                    </div>
                                </div>
                                <a href="{% url 'dashboard:quiz_list' %}" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-project"></i>
                                            <span class="m-l-10">Quizes</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="{% url 'dashboard:logout' %}" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Logout</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                            </div>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>    
            <!-- Header END -->

            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <ul class="side-nav-menu scrollable">
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle" href="javascript:void(0);">
                                <span class="icon-holder">
                                    <i class="anticon anticon-dashboard"></i>
                                </span>
                                <span class="title">Quiz</span>
                                <span class="arrow">
                                    <i class="arrow-icon"></i>
                                </span>
                            </a>
                            <ul class="dropdown-menu" style="display: none;">
                                <li class="">
                                    <a href="{% url 'dashboard:quiz_create' %}">Quiz yaratish</a>
                                </li>
                                <li class="active">
                                    <a href="{% url 'dashboard:quiz_list' %}">Quizlar ro`yhati</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Side Nav END -->              
            {% endif %}

            <!-- Page Container START -->
            <div class="page-container">
                
                {% block content %}
                {% endblock %}
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0">Copyright © 2019 Quiz.</p>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

        </div>
    </div>

    
    <!-- Core Vendors JS -->
    <script src="{% static 'js/vendors.min.js' %}"></script>

    <!-- page js -->
    <script src="{% static 'vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/pages/dashboard-project.js' %}"></script>

    <!-- Core JS -->
    <script src="{% static 'js/app.min.js' %}"></script>


</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<!-- Content Wrapper START -->
         <div class="main-content">
            <div class="page-header no-gutters">
                <div class="d-md-flex align-items-md-center justify-content-between">
                    <div class="media m-v-10 align-items-center">
                        <div class="avatar avatar-image avatar-lg">
                            <img src="{% static 'images/avatars/thumb-3.jpg' %}" alt="">
                        </div>
                        <div class="media-body m-l-15">
                            <h4 class="m-b-0">{{user.username}}!</h4>
                            <span class="text-gray">{% if user.is_staff %}Admin {% else %}Foydalanuvchi{% endif %}</span>
                        </div>
                    </div>
                    <div class="d-md-flex align-items-center d-none">
                        <div class="media align-items-center m-r-40 m-v-5">
                            <div class="font-size-27">
                                <i class="text-primary anticon anticon-profile"></i>
                            </div>
                            <div class="d-flex align-items-center m-l-10">
                                <h2 class="m-b-0 m-r-5">{{quizzes|length}}</h2>
                                <span class="text-gray">Quizzes</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between m-b-15">
                            <h4 class="m-b-0">Quizlar ro`yhati</h4>
                            <div class="card-toolbar">
                                <ul>
                                    <li>
                                        <a class="text-gray" href="{% url 'dashboard:quiz_create' %}">
                                            <button class="btn btn-primary btn-tone m-r-5">Quiz qo`shish</button>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        {% if quizzes %}
                        <div class="m-t-25">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Nom</th>
                                            <th scope="col">Harakatlar</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for q in quizzes %}
                                        <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <td><a href="{% url 'dashboard:quiz_detail' q.code %}">{{q.name}}</a></td>
                                            <td>{{q.all}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>                          
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Wrapper END -->
        
{% endblock %}